stages:
  - test
  - deploy

test:
  stage: test
  image: alpine:3.20
  before_script:
    - apk add --no-cache curl jq
  script:
   - |
     for i in {1..5}; do
      echo "Finding Github CI status for ${CI_COMMIT_SHA}..." && export GITHUB_CI_STATUS=$(curl -s https://api.github.com/repos/EBIvariation/eva-common-pyutils/actions/runs | jq --arg COMMIT_TO_FIND $CI_COMMIT_SHA -r '.workflow_runs | map(select(.head_sha == $COMMIT_TO_FIND and .conclusion == "success"))[0].conclusion') && [[ $GITHUB_CI_STATUS == "success" ]] && echo "Github CI run was successful!"
      if [ $? -ne 0 ]; then
       echo "Retrying..."
       sleep 300
      else
       exit 0
      fi
     done
     exit 1
  environment:
    name: test-env
  only:
    - external_pull_requests
    - tags
    - master


deploy-python-package-production:
  stage: deploy
  image: python:3.11-slim-bullseye
  script:
    - python setup.py sdist
    - twine upload dist/*
  dependencies:
    - test
  variables:
    TWINE_NON_INTERACTIVE: "true"
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  only:
    - tags
